### PR TITLE
1895 docx job type

### PR DESCRIPTION
**Pull request by TylerZeroMaster**
- [ ] openstax/CE#1895

Add the docx job type to database and frontend.

### CODE REVIEW

**Review by m1yag1 — APPROVED** [review]

**Review by therealmarv — APPROVED** [review]

**Comment by therealmarv** [comment]
what about this one failing test? Why does it fail?

**Comment by TylerZeroMaster** [comment]
@therealmarv The failing test was caused by the ui tests. They were not clicking the `create a new job` button as intended. A fix has been merged and I have pulled it into this branch.

**Comment by omehes** [comment]
testing: 20220727.160436
docx option in corgi exists, jobs run and download a complete zip file for all docx files (and for all bundled collections)
docx files looks good

**Comment by omehes** [comment]
verified in corgi prod - 20220801.182716
OK

**Pull request merged**
